version: "3.9"
services:
  client:
    container_name: client
    build:
      context: .
      dockerfile: ./settings/DockerfileClient
    volumes:
      - type: bind
        source: ./client
        target: /client
    ports:
      - 3000:3000
    tty: true
  mecab:
    container_name: mecab
    build:
      context: .
      dockerfile: ./settings/DockerfileMeCab
    volumes:
      - type: bind
        source: ./server-mecab
        target: /server-mecab
    ports:
      - 4000:4000
    tty: true
  cgi:
    container_name: cgi
    build:
      context: .
      dockerfile: ./settings/DockerfileCgi
    ports:
      - 80:80
